# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzXacQg28GVgnYgApT9Yc9F9ECDG3yNH
"""

#Parte 1. Tipos de datos

	#Define tres variables:
		#- Un número entero (int) con tu edad.
		#- Un número decimal (float) con tu altura en metros.
#- Una cadena de texto (str) con tu nombre completo.
Edad =int(19)               # Un número entero (int) con tu edad
Altura =float(1.75)           # Un número decimal (float) con tu altura en metros
nombre = str("missael ramirez")  # Una cadena de texto (str) con tu nombre


#Pregunta: ¿qué función en Python permite conocer el tipo de dato de una variable? Úsala para mostrar los resultados.

type(Edad)
type(Altura)
type(nombre)

#parte 2 operaciones aritmeticas

# Precios de los productos
producto1 = 125.50
producto2 = 89.99
producto3 = 39.75

# Total de la compra
total = producto1 + producto2 + producto3

# Descuento del 15%
descuento = total * 0.15
precio_con_descuento = total - descuento

# IVA del 16%
iva = precio_con_descuento * 0.16

# Total final
total_final = precio_con_descuento + iva

print("Total sin descuento:", total)
print("Descuento aplicado:", descuento)
print("Precio con descuento:", precio_con_descuento)
print("IVA (16%):", iva)
print("Total final a pagar:", total_final)

#¿Qué operador usarías para obtener el residuo de dividir 125 entre 12?
# Operador de residuo
residuo = 125 % 12
print("Residuo de 125 ÷ 12:", residuo)

#parte 3

print("¿Edad mayor a 18?", Edad > 18)
print("¿Producto más caro > 100?", max(producto1, producto2, producto3) > 100)
print("¿Total final <= 200?", total_final <= 200)

#parte 4

# Variables booleanas
pago_tarjeta = True
tiene_descuento = False

print("¿Pagó con tarjeta Y tiene descuento?", pago_tarjeta and tiene_descuento)
print("¿Pagó con tarjeta O tiene descuento?", pago_tarjeta or tiene_descuento)
print("Negación de 'tiene_descuento':", not tiene_descuento)

#parte 5

# Solicita datos al usuario
Edad = int(input("Ingresa tu edad: "))
Altura = float(input("Ingresa tu altura en metros: "))
monto_compra = float(input("Ingresa el monto de tu compra: "))

# Mostrar tipos
print("Tipo de edad:", type(Edad))
print("Tipo de altura:", type(Altura))
print("Tipo de monto de compra:", type(monto_compra))

# Verificaciones
es_mayor_edad = Edad >= 18
compra_mayor_500 = monto_compra > 500

print("¿Es mayor de edad?", es_mayor_edad)
print("¿La compra excede los $500?", compra_mayor_500)
print("¿Mayor de edad Y compra > $500?", es_mayor_edad and compra_mayor_500)